Repository prashant1146/Hactober2022, pull requests merged in 2022-10, with the labels that each got.

#2 Solution of rotate Matrix
  Contibute your leetcode solution here/Rotate_Matrix.cpp
Labels: hactoberfest, hactoberfest-accepted

#5 Solution of largest perimeter triangle #3
  Contibute your leetcode solution here/Largest_Perimeter_Triangle.cpp
Labels: hactoberfest, hactoberfest-accepted, hactoberfest2022

#6 added the required solution of problem
  Contibute your leetcode solution here/largest_perimeter_of_triangle.cpp
Labels: hactoberfest, hactoberfest-accepted, hactoberfest2022

#9 Solution of PR#4
  Contibute your leetcode solution here/Save_your_life.cpp
Labels: hactoberfest, hactoberfest-accepted, hactoberfest2022

#10 Create Student_Report_Card_System.cpp
  Student_Report_Card_System.cpp
Labels: good first issue, hactoberfest, hactoberfest-accepted, hactoberfest2022

#13 Create Delete Node in a linked list || Oct 13
  Contibute your leetcode solution here/Delete Node in a linked list || Oct 13
  Contibute your leetcode solution here/Leetcode #5 Longest Palindromic Substring
Labels: hactoberfest, hactoberfest-accepted, hactoberfest2022

#18 Add binary - leetcode 67
  Contibute your leetcode solution here/0067-add-binary.cpp
Labels: hactoberfest, hactoberfest-accepted, hactoberfest2022

#19 Create #169 majorityElement.cpp
  Contibute your leetcode solution here/#169 majorityElement.cpp
Labels: hactoberfest, hactoberfest-accepted, hactoberfest2022

#22 Pandas_Library_PR#11
  pandas basic functions/Pandas.ipynb
Labels: hactoberfest, hactoberfest-accepted, hactoberfest2022

#24 Create #4 medianOfTwoSortedArrays.cpp
  Contibute your leetcode solution here/#4 medianOfTwoSortedArrays.cpp
Labels: hactoberfest, hactoberfest-accepted, hactoberfest2022

#25 Create basicGraphs.py
  MatplotLib/basicGraphs.py
Labels: hactoberfest, hactoberfest-accepted, hactoberfest2022

#26 Save your life problem solution
  Contibute your leetcode solution here/Save_Your_Life.cpp
Labels: hactoberfest, hactoberfest-accepted, hactoberfest2022

#31 uyl_shortner_#PR23
  urlshortner/shortened_url_dict.pkl
  urlshortner/urlshorten.py
Labels: hactoberfest, hactoberfest-accepted, hactoberfest2022

#38 152. Maximum Product Subarray.cpp
  Contibute your leetcode solution here/152. Maximum Product Subarray.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#48 Created function of seive of eratosthenes
  SieveOfEratosthene.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#40 Sieve of Eratosthenes in python
  Sieve of Eratosthenes in python
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#60 various functions of matplotlib functions file created
  MatplotLib/Various functions of Matplotlib library of Python.ipynb
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#57 binarysearch.py
  binaryserach.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#56 Binary Search in Python
  Binary_Search.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#50 Created program for min diff btw 2 elements in array
  MinimumDiffBtw2Elements.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#43 Created Binary Search in Java
  binarySearch.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#41 Created Linear Search in Java
  linearSearch.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#39 Created move zeros to end
  moveZerosToEnd.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#42 Remove duplicates from sorted array in JAVA
  RemoveDuplicatesFromSortedArray.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#61 Add Sieve of Eratosthene
  Sieve of Eratosthene/SieveOfEratosthene.ipynb
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#51 simple url shortner in golang
  urlshortner/doc.md
  urlshortner/urlshortner.go
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#58 Programpushzero.java by govind sangal
  Programpushzero.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#62 Add MergeSortedLists.java
  MergeSortedLists.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#32 c++ solution for leetcode problem 12_integer_to_roman
  Contibute your leetcode solution here/leetcode_12_integer_to_roman.cpp
  Contibute your leetcode solution here/leetcode_224_basic_calculator_hard.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#63 created find the roots of quadratic equations.
  quadRoots.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#65 Create Binary_search.py
  Binary_search.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#64 created to find and delete repeating number in a given list..
  del_repeating.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#69 Added Bank Currency Printer
  bank.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#68 Create LongestCommonPrefix.py
  LongestCommonPrefix.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#72 Create binary search in python
  binary search in python
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#71 BinarySearch.py
  BinarySearch.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#70 Maximum Product Subarray.cpp added
  Contibute your leetcode solution here/152-Maximum-Product-Subarray.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#73 add code for removing duplicates
  removeduplicates.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#78 Create quadratic_ roots.py
  quadratic_ roots.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#79 Solution of Issue #77
  complexAdd.cpp
  complexAdd.exe
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#81 Solution to issue #67
  issubstr.cpp
  issubstr.exe
  matrixMultiplication.cpp
  matrixMultiplication.exe
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#83 Add two complex numbers
  Add two complex numbers
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#86 Create bracket balancing.cpp
  bracket balancing.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#85 Create s1 is substring of s2 or not code.
  s1 is substring of s2 or not code.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#87 S1 is substring of S2
  S1 is substring of S2
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#88 Create #75 sortColors.cpp
  Contibute your leetcode solution here/#75 sortColors.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#91 SolutionToIsuue #90 (ValidParanthesis)
  validParenthesis.cpp
  validParenthesis.exe
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#92 bracket_balance
  balance_bracket.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#101 avl_tree
  AVL.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#97 Added leetcode Problem 31
  Contibute your leetcode solution here/31_Next_Permutation.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#96 Create a Parenthesis checker using python
  .DS_Store
  Binary_Search.py
  paranthesis.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#95 Added the Python program to find the two roots of a quadratic equation
  MaxProductSubarray.cpp
  RootsOfQuadraticEquation.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#104 [Hacktoberfest 2022] Add reverse number function
  reverse_number.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#105 Binarysearch reccurcive approach
  bs_usingreccursion.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#106 mergesort fuction
  mergesort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#107 Create subarraysearch.cpp
  subarraysearch.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#108 Create 2Dbinarysearch.cpp
  2Dbinarysearch.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#110 Create 169.Majority element
  Contibute your leetcode solution here/169.Majority element
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#111 Create 136 single number
  Contibute your leetcode solution here/136 single number
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#114 Pandas library function-A basic introduction
  Pandas library Functions-A basic Introduction.docx
  Pandas library Functions-A basic Introduction.pdf
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#113 String To ASCII Code Generator
  StringToASCII.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#112 added integer to roman
  Integer to Roman.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
